### ISSUE TITLE
Display schedules do not work.

### ISSUE THREAD

**Issue by luknogal** [mivalsten/raspi-screen-displayer#11]
After selecting the appropriate schedule you can load the file. But you cannot set the display date. 
After setting a suitable date and pressing the send button, a message about a missing page appears. The date itself is not saved.
The calendar to choose from should open at least on the current date as a default. Now it is always January 2019.

**Comment by mivalsten** [comment]
Quick investigation shows that:
1. There is an error in www/post/send_schedule.php file on line 25
```
2020/08/31 22:10:30 [error] 29215#29215: *664424 FastCGI sent in stderr: "PHP message: PHP Recoverable fatal error:  Object of class DateTime could not be converted to string in /srv/inz/www/post/set_schedule.php on line 25" while reading response header from upstream, client: 10.40.126.1, server: , request: "POST /post/set_schedule.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "10.41.64.1", referrer: "http://10.41.64.1/"
```
Should be fairly easy to fix.

2.  Display date is being saved even though there is an error, but there is some error with timezones that needs further investigation. Quick fix might be to change system time zone to GMT.

3. I thought that I set up calendar to display like this, but I'll fix that.

**Comment by mivalsten** [comment]
Update:
1. Is fixed now, I'll push the code to git in a moment.
2. Still investigating.
3. is not an issue, it opens on date of the schedule, if the schedule is empty it opens on current date.

**Comment by mivalsten** [comment]
Final update, 2. is also fixed, scheduler.ps1 is now timezone aware.
